name: Deploy

on: 
  push:
    branches:
      - "main"

jobs:
  redeploy:
    name: Deploying Everything
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        run: |
          echo "${{ secrets.AWS_FREE }}" > key.pem
          chmod 600 key.pem
          
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            cd /DevOps-Practice && git pull

            nvm use v22.22.1

            pnpm install
            pnpm run build
            
            pm2 restart http || pm2 start http
            pm2 restart ws || pm2 start ws
            pm2 restart nextjs-app || pm2 start nextjs-app
            
            pm2 save
          EOF